backend:
  name: github
  repo: anastasiya737/defiyield_docs
  branch: gh-pages
  site_domain: confident-mcclintock-d389ad.netlify.app
media_folder: ".vuepress/public/"
# public_folder: "/media"



collections:
  - name: "dashboard" # Used in routes, e.g., /admin/collections/blog
    label: "Dashboard" # Used in the UI
    folder: "dashboard" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Security" # Used in routes, e.g., /admin/collections/blog
    label: "Security" # Used in the UI
    folder: "security" # The path to the folder where the documents are stored
    file: "index.html"
    create: true # Allow users to create new documents in this collection
    extension: html
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}


